import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Theme, Container, ThemePanel } from "@radix-ui/themes";

import "./globals.css";

import "@radix-ui/themes/styles.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme appearance="dark">
          <Container>{children}</Container>
          {/* <ThemePanel /> */}
        </Theme>
      </body>
    </html>
  );
}
